### PR TITLE
feat: add basic karma infrastructure

### PR DESCRIPTION
**Pull request by frederikprijck**
Closes: #1

### CODE REVIEW

**Comment by juristr** [comment]
LOL, can't keep up with that speed, got work to do LOL. Awesome man. Maybe we should also change the `.travis.yml` s.t. it executes the test as well now. Just to see whether the setup works properly :+1:

**Comment by frederikprijck** [comment]
Consider that done.

**Comment by frederikprijck** [comment]
Oops. Karma is watching the tests. Sorry!

**Comment by frederikprijck** [comment]
I've modified karma.config to not watch the tests.

**Comment by juristr** [comment]
> I've modified karma.config to not watch the tests.

yep :smile: was just about to write you that :wink:

**Comment by frederikprijck** [comment]
Do you want me to add a test script to watch for code changes aside from the `npm test` being used by ci ?
Should we add tslint for karma aswell? Or only use tsling by calling `npm run build(:prod)`?

**Comment by frederikprijck** [comment]
@juristr What do we do with the above comments ?

**Comment by juristr** [comment]
Ya, I'd add a script that watches, like

```
"test.watch": ....
```

and leave `npm test` to be run by the CI container, thus only as single run. thx

**Pull request merged**
